name: Go CD

on:
  push:
    branches: ["master"]
    

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.25'

    - name: Build for Linux
      run: GOOS=linux GOARCH=amd64 go build -o ghost-tunnel-server ./cmd/server

    - name: Deploy to VPS
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.VPS_SSH_HOST }}
        username: ${{ secrets.VPS_SSH_USER }}
        key: ${{ secrets.VPS_SSH_PRIVATE_KEY }}
        source: "ghost-tunnel-server,db/,goose.yaml"
        target: ${{ secrets.VPS_PROJECT_PATH }}
        strip_components: 1

    - name: Restart application on VPS
      uses: appleboy/ssh-action@master
      with:
          host: ${{ secrets.VPS_SSH_HOST }}
          username: ${{ secrets.VPS_SSH_USER }}
          key: ${{ secrets.VPS_SSH_PRIVATE_KEY }}
          script: |
            cd ${{ secrets.VPS_PROJECT_PATH }}
            
            PID=$(pgrep -f "^./ghost-tunnel-server$")
            if [ -n "$PID" ]; then
              echo "Stopping existing server..."
              kill $PID
              sleep 2
            fi
            
            echo "Starting new server in background..."
            nohup ./ghost-tunnel-server > nohup.out 2>&1 &
            
            echo "Deployment script finished."